「検索して調べる」の仕様変更
cfj-afterpillsearch/search-frontend pull request #107
Opened 2023-12-26 04:26 UTC by bp22092

pharmacy-card→pharmacy-card.component.htmlの22行目
[attr.href]="'https://www.google.com/search?q=' + pharmacy.name"を [attr.href]="'https://www.google.com/search?q=' + pharmacy.name +pharmacy.address"に変更した。 Fixes #78

2023-12-26 04:55 UTC, osappy requested changes
プルリクありがとうございます！
2点指摘と1点のアドバイスです。

- 薬局だけでなく、医療機関にも適用してください
- 薬局名と住所の間にスペースを入れてください。

アドバイスとしては、文字列への変数の展開はテンプレートリテラルを使うとよいです。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2024-02-29 10:22 UTC, closed without merging

2024-02-29 10:22 UTC, bp22092 commented
pharmacy-card.component.htmlファイルの22行目を
[attr.href]="'https://www.google.com/search?q=' + pharmacy.name +'  '+pharmacy.address"
に変更
medical-institution-card.component.htmlファイルの26行目を
`[attr.href]="'https://www.google.com/search?q=' + medicalInstitution.name +'  '+ medicalInstitution.address"
に変更

2024-05-23 12:06 UTC, tanimuranaomichi commented
動作確認観点

変更を確認してほしいところ
- 「検索して調べる」で、名前だけでなく住所も入っていること（名前と住所の間にスペースが有ること）

変更されてないことを確認してほしいところ
- 地図
- 電話

2025-06-21 04:35 UTC, tanimuranaomichi commented
動作確認用環境が動いていない
PRを作ってから時間がたったため？と思ったのでPR作り直してみる
そのためにクローズ