都道府県・市区町村を両方選択した場合にのみ検索ボタンを押せるようにする #18
cfj-afterpillsearch/search-frontend pull request #58
Opened 2023-08-05 16:41 UTC by tanimuranaomichi

2023-08-06 08:52 UTC, osappy requested changes
arePrefectureAndMunicipalitySelected()が気になったくらい。
他はLGTMです。

2023-08-06 08:52 UTC, osappy commented on src/app/features/medical-institutions/medical-institutions/medical-institutions.component.html
> +    [disabled]="!arePrefectureAndMunicipalitySelected()"
英語文法的にAreは正しいんだけど、あんまり見たことない。
Boolean返すときは、isXXX()になると思う。

2023-08-06 09:30 UTC, tanimuranaomichi commented on src/app/features/medical-institutions/medical-institutions/medical-institutions.component.html
> +    [disabled]="!arePrefectureAndMunicipalitySelected()"
修正しました！

2023-08-08 13:42 UTC, osappy approved these changes

2023-08-08 13:42 UTC, osappy commented
@tanimuranaomichi LGTM!!

2023-08-08 13:46 UTC, merged